version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pgjson
    environment:
      POSTGRES_USER: igorkoishman
      POSTGRES_PASSWORD: igor1989
      POSTGRES_DB: graphdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # init scripts folder

volumes:
  pgdata: